import Head from "next/head";
import { AiFillGithub, AiFillInstagram, AiFillShopping } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/MyPhoto.png";
import code from "../public/code.png";
import logoReactJs from "../public/icon-react-js.svg";
import logoNextJs from "../public/icon-nextjs.svg";
import logoNodeJs from "../public/icon-node-js.svg";
import logoVueJs from "../public/icon-vue-js.svg";
import logoExpressJs from "../public/icon-express-js.svg";
import logojava from "../public/icon-java.svg";
import design from "../public/design.png";
import logoCorelDraw from "../public/icon-corel-draw-2021.svg";
import logoFigma from "../public/icon-figma.svg";
import Image from "next/image";
import web1 from "../public/project-Laundry.png";
import web2 from "../public/ZeeDax-projek.png";
import sertifikat1 from "../public/sertifikat Hackathon.png";
import sertifikat2 from "../public/sertifikat OOP JavaScript.png";
import sertifikat3 from "../public/sertifikat Seminar.png";
import sertifikat4 from "../public/sertifikat GIT.png";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio Muhamad Fadli</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" bg-white px-4 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">My Portofolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                  onClick={() =>
                    window.open(
                      "https://drive.google.com/file/d/1g6wrOp8eAPf_oVqghUsVJtNVX0EWoXSq/view?usp=sharing",
                      "_blank"
                    )
                  }
                >
                  Resume
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 md:font-medium font-bold dark:text-teal-400 md:text-6xl">
              Muhamad Fadli
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi saya Muhamad Fadli Seorang Developer Web, Android, dan Desktop.
              Saya sangat menyukai dunia IT, terutama dalam bidang pengembangan
              perangkat lunak. dan Saya juga seorang Pengusaha Online
              <span className="text-teal-500"> Seller Shopee </span>
              yang menjual Baju Kaos Pria, Wanita, dan Anak-anak.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://github.com/FuncSmile">
                <AiFillGithub />
              </Link>
              <Link href="https://www.instagram.com/muhfadli6/">
                <AiFillInstagram />
              </Link>
              <Link href="https://shopee.co.id/shop/1385779368">
                <AiFillShopping />
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Kemampuan Saya</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-justify">
              Saya adalah pribadi yang menggabungkan{" "}
              <span className="text-teal-500">kreativitas</span>, logika, dan
              semangat berbagi. Berbekal keahlian di bidang desain, pemrograman,
              dan pengajaran, saya senantiasa menantang diri untuk terus tumbuh.
              Saya senang mengeksplorasi hal-hal baru dan tak ragu membagikan
              wawasan serta pengalaman kepada orang lain—baik melalui kolaborasi
              maupun pengajaran. Bagi saya, belajar adalah proses tanpa akhir,
              dan berbagi adalah bentuk kontribusi terbaik.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-2xl hover:scale-105 ease-in-out duration-100 p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Designs</h3>
              <p className="py-2">
                Membuat desain logo yang menarik dan fungsional adalah passion
                saya. Saya percaya bahwa desain yang baik dapat meningkatkan
                pengalaman pengguna.
              </p>
              <h4 className="py-4 text-teal-600">Aplikasi yang saya gunakan</h4>
              <div className="w-full h-auto flex justify-center gap-8 items-center">
                <Image
                  src={logoCorelDraw}
                  width={40}
                  height={40}
                  title="Corel Draw"
                  alt="Corel Draw"
                />
                <Image
                  src={logoFigma}
                  width={40}
                  height={40}
                  title="Figma"
                  alt="Figma"
                />
              </div>
            </div>
            <div className="text-center shadow-2xl hover:scale-105 ease-in-out duration-100 p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Programming</h3>
              <p className="py-2">
                Mebuat aplikasi web, Android, dan desktop adalah keahlian saya.
                Saya senang menulis kode yang bersih dan efisien untuk
                menciptakan solusi yang inovatif.
              </p>
              <h4 className="py-4 text-teal-600">
                Teknologi yang saya gunakan
              </h4>
              <div className="w-full h-auto flex justify-center gap-8 items-center">
                <Image
                  src={logoNextJs}
                  width={40}
                  height={40}
                  alt="Next.js"
                  placeholder="Next.js"
                />
                <Image
                  src={logoReactJs}
                  width={40}
                  height={40}
                  alt="React.js"
                  placeholder="React.js"
                />
                <Image
                  src={logoVueJs}
                  width={40}
                  height={40}
                  alt="Vue.js"
                  placeholder="Vue.js"
                />
                <Image
                  src={logoExpressJs}
                  width={40}
                  height={40}
                  alt="Express.js"
                  placeholder="Express.js"
                  blurDataURL="lala"
                />
                <Image
                  src={logoNodeJs}
                  width={40}
                  height={40}
                  alt="Node.js"
                  placeholder="Node.js"
                />
                <Image
                  src={logojava}
                  width={40}
                  height={40}
                  alt="Java"
                  placeholder="Java"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Sejak Awal SMK saya sudah mulai belajar tentang pemrograman secara
              <span className="text-teal-500"> otodidak</span>. Dan saya juga
              pernah mengikuti lomba
              <span className="text-teal-500"> Hackathon </span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              ini adalah beberapa proyek yang telah saya kerjakan, baik itu
              proyek pribadi maupun proyek bersama teman-teman saya.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 hover:scale-105 ease-in-out duration-100 bg-white rounded-lg shadow-2xl dark:shadow-lg dark:shadow-slate-50/50 p-8 dark:bg-gradient-to-b dark:from-teal-500 dark:to-transparent dark:bg-transparent">
              <Link href="https://github.com/FuncSmile/kasirLaundry">
                <Image
                  className="rounded-lg object-contain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                />
              </Link>
            </div>
            <div className="basis-1/3 flex-1 hover:scale-105 ease-in-out duration-100 bg-white rounded-lg shadow-2xl dark:shadow-lg dark:shadow-slate-50/50 p-8 dark:bg-gradient-to-b dark:from-teal-500 dark:to-transparent dark:bg-transparent">
              <Image
                className="rounded-lg object-contain"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Sertifikasi</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Saya telah mengikuti beberapa kursus online untuk meningkatkan
              keterampilan saya dalam pengembangan perangkat lunak.
              Kursus-kursus ini mencakup berbagai topik, mulai dari pengembangan
              web hingga desain UI/UX.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Berikut adalah beberapa sertifikasi yang telah saya peroleh:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 hover:scale-105 ease-in-out duration-100 bg-white rounded-lg shadow-2xl dark:shadow-lg dark:shadow-slate-50/50 p-8 dark:bg-gradient-to-b dark:from-teal-500 dark:to-transparent dark:bg-transparent">
              <Link href="https://github.com/FuncSmile/kasirLaundry">
                <Image
                  className="rounded-lg object-contain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={sertifikat1}
                />
              </Link>
            </div>
            <div className="basis-1/3 flex-1 hover:scale-105 ease-in-out duration-100 bg-white rounded-lg shadow-2xl dark:shadow-lg dark:shadow-slate-50/50 p-8 dark:bg-gradient-to-b dark:from-teal-500 dark:to-transparent dark:bg-transparent">
              <Image
                className="rounded-lg object-contain"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={sertifikat2}
              />
            </div>
            <div className="basis-1/3 flex-1 hover:scale-105 ease-in-out duration-100 bg-white rounded-lg shadow-2xl dark:shadow-lg dark:shadow-slate-50/50 p-8 dark:bg-gradient-to-b dark:from-teal-500 dark:to-transparent dark:bg-transparent">
              <Image
                className="rounded-lg object-contain"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={sertifikat3}
              />
            </div>
            <div className="basis-1/3 flex-1 hover:scale-105 ease-in-out duration-100 bg-white rounded-lg shadow-2xl dark:shadow-lg dark:shadow-slate-50/50 p-8 dark:bg-gradient-to-b dark:from-teal-500 dark:to-transparent dark:bg-transparent">
              <Image
                className="rounded-lg object-contain"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={sertifikat4}
              />
            </div>
          </div>
        </section>
      </main>
      <footer className="text-center py-2 bg-gray-200 dark:bg-teal-500 text-gray-700 dark:text-white">
        <p>
          &copy; {new Date().getFullYear()} Muhamad Fadli. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
